<Project>
  <!-- 所有子项目共享的公共属性 -->
  <PropertyGroup>
    <Version>1.3.5</Version>
    <Authors>WindowShare</Authors>
    <Product>WindowShare (窗享)</Product>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
